# Generated by Django 5.2.14 on 2026-05-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Ложь — комментарий скрыт (архив) после истечения времени очисткой.'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Ложь — пост в архиве (Кладбище) после истечения срока или команды очистки.'),
        ),
    ]
