# Generated by Django 5.2.14 on 2026-05-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_is_active_post_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='granted_time_extension',
            field=models.BooleanField(default=False, help_text='Посту уже начислены +4ч за лайк этого пользователя (не откатывается).'),
        ),
        migrations.AddField(
            model_name='like',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
