# Generated by Django 5.2.14 on 2026-05-15 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def dedupe_top_level_comments(apps, schema_editor):
    Comment = apps.get_model("forum", "Comment")
    first_by_key = {}
    for comment in Comment.objects.filter(parent__isnull=True).order_by("created_at", "pk"):
        key = (comment.post_id, comment.author_id)
        if key in first_by_key:
            comment.parent_id = first_by_key[key]
            comment.save(update_fields=["parent_id"])
        else:
            first_by_key[key] = comment.pk


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('acceleration', 'Ускорение'), ('stasis', 'Стазис')], max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='approval_reward_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='granted_golden_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_golden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='granted_time_extension',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(dedupe_top_level_comments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('post', 'author'), name='uniq_top_level_comment_per_user_post'),
        ),
    ]
