# Generated by Django 5.2.14 on 2026-05-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_globalevent_comment_approval_reward_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalEvent',
        ),
    ]
