# Generated by Django 5.2.14 on 2026-05-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_post_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=11, unique=True),
        ),
    ]
