# Generated by Django 5.2.14 on 2026-05-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_title_max_50'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='uniq_top_level_comment_per_user_post',
        ),
    ]
