# Generated by Django 5.2.14 on 2026-07-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_update_global_node_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='node',
            name='header',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='post',
            name='gif',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
