# Generated by Django 5.2.14 on 2026-07-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_node_avatar_node_header_post_audio_post_gif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gif',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
