# Generated by Django 5.2.14 on 2026-05-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_quest_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_basic_colors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_gold_color',
            field=models.BooleanField(default=False),
        ),
    ]
