# Generated by Django 6.0.5 on 2026-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_owned_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyquestcycle',
            name='comment_streak_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdailyquestcycle',
            name='comment_streak_post_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userdailyquestcycle',
            name='near_death_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdailyquestcycle',
            name='post_and_earn_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdailyquestcycle',
            name='post_and_earn_tracked_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(blank=True, choices=[('', 'По умолчанию'), ('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зелёный'), ('gold', 'Золотой'), ('ice', 'Ледяное сияние'), ('matrix', 'Матрица'), ('sunset', 'Закат энтропии')], default='', max_length=16),
        ),
    ]
