# Generated by Django 5.2.14 on 2026-07-17 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userdailyquestcycle_comment_streak_done_and_more'),
        ('forum', '0012_update_global_node_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('post_liked', 'Лайк поста'), ('post_dying', 'Пост умирает'), ('quest_complete', 'Квест выполнен'), ('node_random_post', 'Рандомный пост из узла')], max_length=20),
        ),
        migrations.CreateModel(
            name='NodeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='forum.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'node'), name='uniq_user_node_subscription')],
            },
        ),
    ]
