# Generated by Django 5.2.14 on 2026-07-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('post_liked', 'Лайк поста'), ('post_dying', 'Пост умирает'), ('quest_complete', 'Квест выполнен'), ('node_random_post', 'Рекомендация поста'), ('mention', 'Упоминание')], max_length=20),
        ),
    ]
