# Generated by Django 5.2.14 on 2026-07-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('post_liked', 'Лайк поста'), ('post_dying', 'Пост умирает'), ('quest_complete', 'Квест выполнен'), ('node_random_post', 'Рекомендация поста'), ('node_inactive', 'Узел без активности'), ('new_comment', 'Новый комментарий'), ('comment_reply', 'Ответ на комментарий'), ('mention', 'Упоминание'), ('ban', 'Бан')], max_length=20),
        ),
    ]
