# Generated by Django 5.2.14 on 2026-07-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_owned_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_anonymous_mode',
            field=models.BooleanField(default=False, help_text='Анонимный режим: имя скрывается в постах и комментариях'),
        ),
    ]
