# Generated by Django 5.2.14 on 2026-07-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Рассылать уведомления на почту'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email подтверждён'),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_awarded',
            field=models.BooleanField(default=True, help_text='50 токенов за регистрацию уже начислены'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('post_liked', 'Лайк поста'), ('post_dying', 'Пост умирает'), ('quest_complete', 'Квест выполнен'), ('node_random_post', 'Рекомендация поста'), ('node_inactive', 'Узел без активности'), ('new_comment', 'Новый комментарий'), ('comment_reply', 'Ответ на комментарий'), ('mention', 'Упоминание'), ('ban', 'Бан'), ('complaint', 'Жалоба')], max_length=20),
        ),
    ]
