# Generated by Django 5.2.14 on 2026-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_email_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='discount_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='Скидка в процентах (0-100). Устанавливается администратором.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(blank=True, choices=[('', 'По умолчанию'), ('red', 'Алый закат'), ('purple', 'Сиреневый туман'), ('pink', 'Неоновая роза'), ('gray', 'Пепел эпохи'), ('metal', 'Жидкий металл'), ('blue', 'Бездонная синева'), ('green', 'Зелёный'), ('gold', 'Золотой'), ('ice', 'Ледяное сияние'), ('matrix', 'Матрица'), ('sunset', 'Закат энтропии')], default='', max_length=16),
        ),
    ]
