# Generated by Django 5.2.14 on 2026-07-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_shopitem_discount_pct_alter_user_profile_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_free_post',
        ),
        migrations.AddField(
            model_name='user',
            name='free_posts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Накопленные бесплатные посты'),
        ),
    ]
